# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e07893d2b88809ddd44cbe7de479f9daa59aa6dfe2e924bd09555606e7c1284a606458d3378a82ead0e2c4b7c706e98ae96a96d74fe6a355f4757d4ae6d456

test:
  secret_key_base: 7451fa5f883a37db3b04791c38d56d3f1adb6eb9c032d8317775eebc35ca3fde6356426142f757f73ac2ddaa1d5d78f45a81dfae34543eeeb5ca0c3efeb8d257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
